### PR TITLE
CefSharp website V1

### PR DESCRIPTION
**Pull request by hgupta9**
I've just designed a simple website and Logo for CefSharp.

* Feature list with diagrams per entry
* Nice site header with new logo
* Links to "getting started" and Nuget packages

The website can be previewed here:
http://hgupta9.github.io/CefsharpSite/

### CODE REVIEW

**Comment by amaitland** [comment]
Thanks :+1: Will create a follow up `PR` with my proposed changes.

**Comment by hgupta9** [comment]
When will you be accepting this PR? I thought you have to accept it for it to come online? Unless you are going to wait until its all perfectly final before putting it up?

**Comment by amaitland** [comment]
> You merged it! So its online?

It should be. See http://cefsharp.github.io

**Comment by perlun** [comment]
Should we link to this also from the CefSharp main repo?

(Yes, I'm still around, lurking in the background a bit. :wink:)

**Comment by amaitland** [comment]
> Should we link to this also from the CefSharp main repo?

Yep :+1: 

Should your suggestion from https://github.com/cefsharp/CefSharp/commit/9ece6dcbbde6cf5c55428937a0971cef18b6dd0e#commitcomment-14742804 be actioned first?

> (Yes, I'm still around, lurking in the background a bit. :wink:)

It's been a while :smile:  How's things?

**Comment by perlun** [comment]
> Should your suggestion from cefsharp/CefSharp@9ece6dc#commitcomment-14742804 be actioned first?

Yep, it would be nice. If you like, feel free to do it. But like you say, maintaining code examples in html code pretty much sucks.

> It's been a while  How's things?

Things are good! Doing a lot of coding still, but in other areas. Quite a bit of Ruby/HTML/CoffeeScript lately. 

https://wakatime.com

:wink: 

Still using CefSharp, we rely quite heavily on it actually. But since the project is doing so well during the last year or so, I haven't really had to step in that much. You guys are doing a **tremedenous job**. Keep up the good work Alex, and others as well!

**Pull request merged**
