### PR TITLE
CefSharp website V2

### PR DESCRIPTION
**Pull request by hgupta9**
I've made a big update to the website. Please accept the PR as I am now happy with the styling. I will keep making changes (as needed) and submit them in future PRs.

- Style changes
  - Nice blue "internet" image on header
  - Background color is soft chromium blue
  - Logo has soft shadows
- 3D menu on header (anything to be added here?)
  - Menu buttons are white, go dark on rollover
  - Menu buttons are lowercase, also "wiki" and "github" added
- Content changes
 - New sections : Flavors and Docs
 - BSD info added into Open Source section

Demo here:

http://hgupta9.github.io/CefsharpSite/

### CODE REVIEW

**Comment by hgupta9** [comment]
When are you planning on committing this. Are there any issues with it? I've just changed the styling and the info a bit.

**Comment by hgupta9** [comment]
@amaitland - Oh and please remember to press F5 once or twice if it looks like a mess. Github Pages has a habit of using the cached version until you do that. 

http://hgupta9.github.io/CefsharpSite/

**Comment by hgupta9** [comment]
@amaitland - The current version I submitted is here:



And an alternate version with the header white is here:



If you like the alternate, then tell me and I'll submit that into the repo before you commit this.

**Comment by amaitland** [comment]
@hgupta9 I think it's fine for now, thanks :+1:

**Pull request merged**
